---
name: Lint Code Base

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy linter settings
        run: |
          mkdir .github/linters
          cp .markdownlint.json .github/linters/

      - name: Lint Code Base
        uses: github/super-linter@v3.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
