---
name: Lint Code Base

on:
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy linter settings
        run: |
          mkdir .github/linters
          cp .markdown-lint.yml .github/linters/

      - name: Lint Code Base
        uses: github/super-linter@v3.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
